name: diffie_hellman
description: Dart implementation of modular DH groups. Based on PKCS#3.
version: 0.1.1
repository: https://github.com/mrpurpleknight/diffie_hellman
homepage: https://pub.dev/packages/diffie_hellman

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter: