name: diffie_hellman
description: Pure Dart implementation of modular DH groups. Based on PKCS#3.
version: 0.0.2
repository: https://github.com/mrpurpleknight/diffie_hellman
homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  pointycastle: ^3.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter: